module.exports = [ {
    id: "1",
    title: "Se7en",
    director: "David Fincher",
    year: 1995,
    rating: 8.7,
    watched: true,
}, {
    id: "2",
    title: "Fight Club",
    director: "David Fincher",
    year: 1999,
    rating: 8.8,
    watched: false,
}, {
    id: "3",
    title: "The Godfather",
    director: "Francis Ford Copolla",
    year: 1972,
    rating: 9.0,
    watched: false,
},
{
    id: "4",
    title: "The Godfather: Part II",
    director: "Francis Ford Copolla",
    year: 1974,
    rating: 8.9,
    watched: false,
},
{
    id: "5",
    title: "Pulp Fiction",
    director: "Quentin Tarantino",
    year: 1994,
    rating: 8.9,
    watched: false,
},
{
    id: "6",
    title: "Forest Gump",
    director: "Robert Zemeckis",
    year: 1994,
    rating: 8.8,
    watched: false,
} ];
